data:
  drop_last: false
  is_DDP: true
  is_meta: false
  num_gpus: 2
  num_query: 15
  record_root: /dev/shm/wuhao
  test_batchsize: 16
  test_num_task: 2000
  test_shot: 5
  train_batchsize: 128
  train_dataset: ilsvrc_2012
  train_num_workers: 24
  val_batchsize: 2
  val_num_task: 1200
  val_num_workers: 16
  val_shot: 5
  val_test_dataset: ilsvrc_2012
  way: 5
datamodule_name: Simple_MD_datamodule
is_test: false
load_pretrained: false
model:
  backbone_name: timm_models.swin_tiny_patch4_window7_224
  decay_scheduler: cosine
  lr: 0.05
  num_classes: 712
  num_query: 15
  optim_type: adam
  task_classifier_name: proto_head
  task_classifier_params:
    learn_scale: false
    metric: cosine
    normalize: false
  test_batch_size_per_gpu: 8
  test_shot: 5
  use_pickle: false
  val_batch_size_per_gpu: 1
  val_shot: 5
  way: 5
  weight_decay: 0.0005
model_name: CE_pretrain
trainer:
  accelerator: ddp
  callbacks:
  - class_path: pytorch_lightning.callbacks.LearningRateMonitor
    init_args:
      logging_interval: step
  - class_path: pytorch_lightning.callbacks.ModelCheckpoint
    init_args:
      mode: max
      monitor: val/acc
      save_last: true
      verbose: true
  - class_path: callbacks.SetSeedCallback
    init_args:
      is_DDP: true
      seed: 20
  fast_dev_run: false
  gpus:
  - 2
  - 3
  logger:
    class_path: pytorch_lightning.loggers.TensorBoardLogger
    init_args:
      name: CE_pretrain
      save_dir: ./results
  max_epochs: 100
  plugins:
  - class_path: plugins.modified_DDPPlugin
  replace_sampler_ddp: false
  resume_from_checkpoint: null
  sync_batchnorm: true
